# -*- encoding:utf-8 Mode: POLY-ORG;  -*- --- 
#+Startup: noindent
#+PROPERTY:    header-args        :results silent   :eval no-export   :comments org
#+OPTIONS:     num:nil toc:nil todo:nil tasks:nil tags:nil
#+OPTIONS:     skip:nil author:nil email:nil creator:nil timestamp:t
#+INFOJS_OPT:  view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
* Table of Contents                                                   :TOC:
- [[#introduction][Introduction]]
- [[#usage][Usage]]
- [[#license][License]]

* Introduction
This is a clojure library designed to extend the clojure syntax 
so it can load org file as source file directly.

The implementation details of [[https://github.com/jingtaozf/literate-clojure][literate-clojure]] is in file [[./src/literate_clojure/core.org][core.org]] ([[./src/literate_clojure/core.pdf][pdf version]]).

This library is provided to make litrate programming more happy in clojure,without
pain of tangling code from org files.

* Usage
To use this library, please add dependence in your [[./demo/project.clj][project.clj]]:
#+BEGIN_SRC clojure
:dependencies [[org.clojure/clojure "1.9.0"]
                 [literate-clojure "0.0.1"]]
#+END_SRC

Then in one of your [[./demo/src/demo/core.clj][source file]],add the following codes to install the org syntax for clojure reader:
#+BEGIN_SRC clojure
(require 'literate-clojure.core)
(literate-clojure.core/install-org-dispatcher)
(load-file "src/demo/core.org")
#+END_SRC
Now you can use [[./demo/src/demo/core.org][core.org]] to write your documentation and source codes together,
and any codes in [[./demo/src/demo/core.org][core.org]] will be loaded automatically.

The org files must start with a sharp and a space, for example I usually add the following line
to the beginning of an org file:
#+BEGIN_SRC org
# -*- encoding:utf-8 Mode: POLY-ORG;  -*- --- 
#+END_SRC
It will use Emacs library [[https://github.com/polymode/poly-org][poly-org-mode]] which is a lightweight library 
to support multiple major mode in one file,
so you can edit clojure code natively in an org file.

* License

Copyright © 2018 Jingtao Xu

This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0.

This Source Code may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License, v. 2.0 are satisfied: GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or (at your
option) any later version, with the GNU Classpath Exception which is available
at https://www.gnu.org/software/classpath/license.html.
